import type { VehicleCard } from '@/lib/types'

export const VEHICLES: VehicleCard[] = [
  {
    id: 1,
    slug: 'standard-sedan',
    name: 'Standard Sedan',
    category: 'Everyday standard',
    description: 'Quiet, quick, and reliable for solo or paired trips.',
    price: 38,
    unit: 'transfer',
    rating: 4.9,
    image: '/standard-sedan.jpg',
    featured: true,
  },
  {
    id: 2,
    slug: 'executive-suv',
    name: 'Executive SUV',
    category: 'Groups & luggage',
    description: 'More room for groups, bags, or a longer stretch of road.',
    price: 74,
    unit: 'transfer',
    rating: 4.8,
    image: '/executive-suv.jpg',
  },
  {
    id: 3,
    slug: 'luxury-sedan',
    name: 'Luxury Sedan',
    category: 'Flagship car',
    description: 'Senior chauffeur, reserved for the trips that matter most.',
    price: 82,
    unit: 'transfer',
    rating: 4.9,
    image: '/luxury-sedan.jpg',
  },
  {
    id: 4,
    slug: 'business-class',
    name: 'Business Class',
    category: 'Regular travel',
    description: 'A balance of comfort and value for frequent trips.',
    price: 64,
    unit: 'transfer',
    rating: 4.8,
    image: '/buisness-class.jpg',
  },
]
