import type { VehicleCard } from '@/lib/types'

export const VEHICLES: VehicleCard[] = [
  {
    id: 1,
    slug: 'standard-cars',
    name: 'Standard Cars',
    category: 'Business Class · Executive Sedan · First Class Sedan',
    description: 'Discreet, comfortable saloons for daily transfers and business travel.',
    image: '/fleet/standard-sedan-home.png',
    passengers: '1-3',
    featured: true,
  },
  {
    id: 2,
    slug: 'suv',
    name: 'SUV',
    category: 'Premium SUV · Luxury SUV · Full-Size Luxury SUV',
    description: 'Commanding presence and space, suited to executive and family travel alike.',
    image: '/fleet/suv-home.png',
    passengers: '1-6',
  },
  {
    id: 3,
    slug: 'mpv',
    name: 'MPV',
    category: 'Business MPV · Luxury MPV',
    description: 'Generous cabin comfort for small groups travelling together in style.',
    image: '/fleet/standard-mpv-home.png',
    passengers: '1-7',
  },
  {
    id: 4,
    slug: 'mini-vans',
    name: 'Mini Vans',
    category: 'Standard Mini Van · VIP Mini Van',
    description: 'Flexible, well-appointed transport for groups of up to seven.',
    image: '/fleet/luxury-mini-van-home.png',
    passengers: '1-7',
  },
  {
    id: 5,
    slug: 'luxury-sedan',
    name: 'Luxury Sedan',
    category: 'First Class · Executive Sedan · VIP Transfers',
    description: 'The highest standard of chauffeured travel with elegance, privacy, and uncompromising comfort.',
    image: '/fleet/luxury-sedan-home.png',
    passengers: '1-3',
  },
  {
    id: 6,
    slug: 'luxury-vans',
    name: 'Luxury Vans',
    category: 'Executive Van · VIP Sprinter',
    description: 'Boardroom-grade interiors for VVIP groups and roadshow travel.',
    image: '/fleet/luxury-mini-van-home.png',
    passengers: '1-7',
  },
  {
    id: 7,
    slug: 'mini-buses',
    name: 'Mini Buses',
    category: '14-Seater · 22-Seater',
    description: 'Comfortable group mobility for delegations, crews, and events.',
    image: '/fleet/mini-coach-home.png',
    passengers: '1-22',
  },
  {
    id: 8,
    slug: 'coaches',
    name: 'Coaches',
    category: 'Standard Coach · Luxury Motor Coach',
    description: 'Full-size coaches for conferences, large events, and group logistics.',
    image: '/fleet/luxury-coach-home.png',
    passengers: '1-50',
  },
]
